const ACTION_TYPES = {
  //counterA
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_STEP: "SET_STEP",
  //toDo
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
};

export default ACTION_TYPES;
